# Generated by Django 4.2.16 on 2025-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boqcategory",
            options={
                "ordering": ["nom"],
                "verbose_name": "Catégorie BOQ",
                "verbose_name_plural": "Catégories BOQ",
            },
        ),
        migrations.AlterUniqueTogether(
            name="boqcategory",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="boqcategory",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Code catégorie"
            ),
        ),
        migrations.RemoveField(
            model_name="boqcategory",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="boqcategory",
            name="ordre",
        ),
    ]
