# Generated by Django 4.2.16 on 2025-11-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0002_remove_operator_ordre_from_boqcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskdefinition",
            options={
                "ordering": ["code"],
                "verbose_name": "Définition de tâche",
                "verbose_name_plural": "Définitions de tâches",
            },
        ),
        migrations.AlterUniqueTogether(
            name="taskdefinition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="taskdefinition",
            name="boq_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                to="deployment.boqitem",
                verbose_name="Articles BOQ",
            ),
        ),
        migrations.AlterField(
            model_name="taskdefinition",
            name="code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Code de la tâche"
            ),
        ),
        migrations.RemoveField(
            model_name="taskdefinition",
            name="boq_item",
        ),
    ]
