# Generated by Django 4.2.16 on 2025-11-24 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0003_change_taskdefinition_to_manytomany"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="valeur_unite",
            field=models.IntegerField(
                default=1,
                help_text="Valeur numérique de l'unité (ex: 1 pour unité simple, 100 pour centaine)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Valeur de l'unité",
            ),
        ),
        migrations.AddField(
            model_name="projectplanning",
            name="valeur_unite",
            field=models.IntegerField(
                default=1,
                help_text="Valeur numérique de l'unité (ex: 1 pour unité simple, 100 pour centaine)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Valeur de l'unité",
            ),
        ),
        migrations.AddField(
            model_name="taskplanning",
            name="valeur_unite",
            field=models.IntegerField(
                default=1,
                help_text="Valeur numérique de l'unité (ex: 1 pour unité simple, 100 pour centaine)",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Valeur de l'unité",
            ),
        ),
    ]
