# Generated by Django 4.2.16 on 2025-11-26 10:58

from django.db import migrations, models
import django.db.models.deletion


def create_initial_specialites(apps, schema_editor):
    """Crée les spécialités de base."""
    Specialite = apps.get_model('deployment', 'Specialite')

    specialites_data = [
        {'code': 'GC', 'nom': 'Génie Civil', 'description': 'Travaux de génie civil : tranchées, chambres, fourreaux', 'couleur': '#8B4513', 'ordre': 1},
        {'code': 'RESEAU', 'nom': 'Travaux de réseau', 'description': 'Installation de câbles, pose aérienne et souterraine', 'couleur': '#4169E1', 'ordre': 2},
        {'code': 'FO', 'nom': 'Fibre Optique', 'description': 'Installation et déploiement de fibre optique', 'couleur': '#FF8C00', 'ordre': 3},
        {'code': 'SOUDURE', 'nom': 'Soudure FO', 'description': 'Soudure et raccordement de fibres optiques', 'couleur': '#DC143C', 'ordre': 4},
        {'code': 'MESURE', 'nom': 'Mesures et tests', 'description': 'Tests de réflectométrie, mesures de perte, validation réseau', 'couleur': '#9370DB', 'ordre': 5},
        {'code': 'POLY', 'nom': 'Polyvalent', 'description': 'Technicien polyvalent capable d\'intervenir sur plusieurs domaines', 'couleur': '#32CD32', 'ordre': 6},
    ]

    for data in specialites_data:
        Specialite.objects.get_or_create(
            code=data['code'],
            defaults={
                'nom': data['nom'],
                'description': data['description'],
                'couleur': data['couleur'],
                'ordre': data['ordre'],
                'is_active': True
            }
        )


def migrate_technician_specialites(apps, schema_editor):
    """
    Migre les spécialités des techniciens de l'ancien format (CharField avec choix)
    vers le nouveau format (ForeignKey vers Specialite).
    """
    Technician = apps.get_model('deployment', 'Technician')
    Specialite = apps.get_model('deployment', 'Specialite')

    # Mapping des anciens codes vers les nouveaux codes
    code_mapping = {
        'gc': 'GC',
        'reseau': 'RESEAU',
        'fo': 'FO',
        'soudure': 'SOUDURE',
        'mesure': 'MESURE',
        'polyvalent': 'POLY',
    }

    # Migrer tous les techniciens existants
    for technician in Technician.objects.all():
        if hasattr(technician, 'specialite'):
            old_code = technician.specialite
            new_code = code_mapping.get(old_code, 'POLY')  # Par défaut: Polyvalent

            try:
                specialite = Specialite.objects.get(code=new_code)
                # La mise à jour sera faite après le changement de type du champ
            except Specialite.DoesNotExist:
                pass  # La spécialité sera créée par create_initial_specialites


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0004_add_valeur_unite_to_models"),
    ]

    operations = [
        # Étape 1 : Créer le modèle Specialite
        migrations.CreateModel(
            name="Specialite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique de la spécialité (ex: GC, FO, SOUD)",
                        max_length=20,
                        unique=True,
                        verbose_name="Code spécialité",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la spécialité"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#000000",
                        help_text="Code couleur hexadécimal (ex: #FF5733)",
                        max_length=7,
                        verbose_name="Couleur d'identification",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Spécialité",
                "verbose_name_plural": "Spécialités",
                "ordering": ["ordre", "nom"],
            },
        ),

        # Étape 2 : Créer les spécialités de base
        migrations.RunPython(
            create_initial_specialites,
            reverse_code=migrations.RunPython.noop
        ),

        # Étape 3 : Transformer le champ specialite en ForeignKey
        # Note: Cette opération nécessite que la table Technician soit vide
        # ou que toutes les valeurs de specialite correspondent à des codes valides
        migrations.AlterField(
            model_name="technician",
            name="specialite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technicians",
                to="deployment.specialite",
                verbose_name="Spécialité",
                null=True,  # Temporairement nullable
                blank=True
            ),
        ),
    ]
