# Generated by Django 4.2.16 on 2025-11-27 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0005_add_specialite_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="coordonnateur",
        ),
    ]
