# Generated by Django 4.2.16 on 2025-11-30 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("deployment", "0006_remove_coordonnateur_and_fix_specialite"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique (ex: BOM, MAP, SYNOPTIQUE, AUTRES)",
                        max_length=20,
                        unique=True,
                        verbose_name="Code du type",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom du type de document"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de document",
                "verbose_name_plural": "Types de documents",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom du document"),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="projects/documents/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version du document (ex: v1.0, v2.1)",
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
                (
                    "taille_fichier",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (octets)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="deployment.project",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "type_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="deployment.typedocument",
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="users.profile",
                        verbose_name="Uploadé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de projet",
                "verbose_name_plural": "Documents de projets",
                "ordering": ["-date_upload"],
            },
        ),
    ]
