# Generated by Django 4.2.16 on 2025-11-30 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0007_typedocument_projectdocument"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectdocument",
            old_name="uploaded_by",
            new_name="uploaded_by_profil",
        ),
    ]
