# Generated by Django 4.2.16 on 2025-11-30 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0008_rename_uploaded_by_to_uploaded_by_profil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="bom",
        ),
        migrations.RemoveField(
            model_name="project",
            name="plan_map",
        ),
        migrations.RemoveField(
            model_name="project",
            name="plan_synoptique",
        ),
    ]
