# Generated by Django 4.2.16 on 2025-11-13 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique du module (ex: deployment, b2b, inventory)",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom du module", max_length=100, verbose_name="Nom"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du module",
                        verbose_name="Description",
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(
                        default=0,
                        help_text="Ordre d'affichage du module dans l'interface",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "db_table": "modules",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique de la permission (ex: chantier.create, b2b.view)",
                        max_length=100,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la permission",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée de la permission",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si la permission est active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="Module auquel appartient cette permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="users.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "ordering": ["module__ordre", "code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique du rôle (ex: admin_deployment, superviseur_terrain)",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom du rôle", max_length=100, verbose_name="Nom"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du rôle",
                        verbose_name="Description",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions associées à ce rôle",
                        related_name="roles",
                        to="users.permission",
                        verbose_name="Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle",
                "verbose_name_plural": "Rôles",
                "db_table": "roles",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique de l'utilisateur (ex: AIV001)",
                        max_length=20,
                        unique=True,
                        verbose_name="Code utilisateur",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de famille", max_length=100, verbose_name="Nom"
                    ),
                ),
                (
                    "prenoms",
                    models.CharField(
                        help_text="Prénom(s)", max_length=100, verbose_name="Prénoms"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone (format: +225XXXXXXXXXX)",
                        max_length=20,
                        null=True,
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo de profil de l'utilisateur",
                        null=True,
                        upload_to="users/photos/%Y/%m/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPERADMIN", "Super Administrateur"),
                            ("ADMIN", "Administrateur"),
                            ("COORDONNATEUR", "Coordonnateur"),
                            ("STOCKMAN", "Gestionnaire de Stock"),
                            ("SUPERVISEUR", "Superviseur"),
                        ],
                        default="SUPERVISEUR",
                        help_text="Rôle de l'utilisateur dans l'application",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "fonction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DG", "Directeur Général"),
                            ("DT", "Directeur Technique"),
                            ("CHEF_PROJET", "Chef de Projet"),
                            ("AUTRE", "Autre"),
                        ],
                        help_text="Fonction (pour les administrateurs)",
                        max_length=20,
                        null=True,
                        verbose_name="Fonction",
                    ),
                ),
                (
                    "custom_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions additionnelles spécifiques à cet utilisateur",
                        related_name="profiles",
                        to="users.permission",
                        verbose_name="Permissions personnalisées",
                    ),
                ),
                (
                    "superieur_hierarchique",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supérieur hiérarchique direct",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordonnés",
                        to="users.profile",
                        verbose_name="Supérieur hiérarchique",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Compte utilisateur Django associé",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Utilisateur",
                "verbose_name_plural": "Profils Utilisateurs",
                "db_table": "profiles",
                "ordering": ["nom", "prenoms"],
                "indexes": [
                    models.Index(fields=["code"], name="idx_profile_code"),
                    models.Index(fields=["role"], name="idx_profile_role"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["code"], name="idx_permission_code"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["module"], name="idx_permission_module"),
        ),
    ]
